before_script:
    - chmod +x ./demo/gradlew

build:
  image: openjdk:8-jdk
  stage: build
  script:
    - ./gradlew clean build
  allow_failure: false
  artifacts:
      paths:
      - build/libs/
  cache:
    paths:
    - src/main/js/node_modules/
    - nodejs/
    - src/main/js/.sass-cache/
    - src/main/js/vendor/
    - src/ratpack/public/

test:
  image: openjdk:8-jdk-alpine
  stage: test
  before_script:
    - docker info
    - docker-compose --version
  script:
    - ./gradlew e2eTests
  artifacts:
    when: always
    paths:
      - build/test-results/
      - build/reports/
      - build/geb-reports/
